# Generated by Django 2.2 on 2021-03-02 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageBucket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.ImageField(blank=True, null=True, upload_to='products/images')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='picture',
            field=models.ManyToManyField(blank=True, null=True, to='products.ImageBucket'),
        ),
    ]
