# Generated by Django 2.2 on 2021-03-04 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210302_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='brand_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Category'),
        ),
    ]
