# Generated by Django 2.2 on 2021-03-08 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20210304_1643'),
    ]

    operations = [
        migrations.CreateModel(
            name='Variants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('size', models.CharField(blank=True, choices=[('not applicable', 'not applicable'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large')], default='not applicable', max_length=50, null=True)),
                ('color', models.CharField(blank=True, default='not applicable', max_length=70, null=True)),
                ('quantity', models.IntegerField(blank=True, default=10, null=True)),
                ('vairant_availability', models.CharField(choices=[('available', 'Available'), ('not_available', 'Not Available')], default='available', max_length=70)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='color',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
        migrations.AddField(
            model_name='product',
            name='variants',
            field=models.ManyToManyField(blank=True, null=True, related_name='products', to='products.Variants'),
        ),
    ]
