# Generated by Django 2.2 on 2021-03-08 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20210308_1144'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='variants',
            options={'verbose_name_plural': 'Variants'},
        ),
    ]
