# Generated by Django 2.2 on 2021-03-14 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20210309_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='variants',
            name='product_id',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
