# Generated by Django 2.2 on 2021-03-15 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20210314_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagebucket',
            name='pic_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='main_product_image',
            field=models.ImageField(blank=True, null=True, upload_to='products/images'),
        ),
        migrations.AlterField(
            model_name='product',
            name='picture',
            field=models.ManyToManyField(blank=True, null=True, to='products.ImageBucket', verbose_name='Add extra 3 images'),
        ),
    ]
