# Generated by Django 2.2 on 2021-03-16 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20210315_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='variants',
            name='variant_image',
            field=models.ImageField(blank=True, upload_to='products/images'),
        ),
    ]
