# Generated by Django 2.2 on 2021-03-21 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_product_merchant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variants',
            old_name='vairant_availability',
            new_name='variant_availability',
        ),
    ]
