# Generated by Django 2.2 on 2021-04-19 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_auto_20210419_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default=-1, max_length=200),
            preserve_default=False,
        ),
    ]
