# Generated by Django 2.2 on 2021-05-03 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_auto_20210429_1227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='brand_category',
        ),
        migrations.AddField(
            model_name='brand',
            name='brand_category',
            field=models.ManyToManyField(blank=True, null=True, to='products.Category'),
        ),
    ]
