# Generated by Django 2.2 on 2021-05-20 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_auto_20210503_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variants',
            name='variant_image',
            field=models.ImageField(blank=True, null=True, upload_to='products/images'),
        ),
    ]
