# Generated by Django 2.2 on 2021-02-22 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_billingdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='billing_details',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='billing_details', to='orders.BillingDetails'),
        ),
    ]
