# Generated by Django 2.2 on 2021-02-22 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_billing_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='billing_details',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order', to='orders.BillingDetails'),
        ),
    ]
