# Generated by Django 2.2 on 2021-02-25 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20210222_1730'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='billing_details',
        ),
    ]
