# Generated by Django 2.2 on 2021-02-17 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20210217_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlistitems',
            name='wishlist',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='wishlistitems', to='orders.Cart'),
            preserve_default=False,
        ),
    ]
