# Generated by Django 2.2 on 2021-02-17 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_wishlistitems_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlistitems',
            name='wishlist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlistitems', to='orders.WishList'),
        ),
    ]
