# Generated by Django 2.2 on 2021-02-28 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_auto_20210228_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='billing_details',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order', to='orders.BillingDetails'),
        ),
    ]
