# Generated by Django 2.2 on 2021-03-01 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_auto_20210228_1621'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='billing_details',
        ),
        migrations.AddField(
            model_name='billingdetails',
            name='order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='billing_details', to='orders.Order'),
        ),
    ]
