# Generated by Django 2.2 on 2021-03-04 05:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0016_billingdetails_payment_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlistitems',
            name='wishlist',
        ),
        migrations.AddField(
            model_name='wishlistitems',
            name='owner',
            field=models.ForeignKey(blank=True, default=-1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
