# Generated by Django 2.2 on 2021-03-04 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_auto_20210304_1048'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='billingdetails',
            options={'verbose_name_plural': 'Shipping Address'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name_plural': 'Orders'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name_plural': 'Cart Items'},
        ),
        migrations.AlterModelOptions(
            name='wishlistitems',
            options={'verbose_name_plural': 'WishList'},
        ),
    ]
