# Generated by Django 2.2 on 2021-03-09 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20210309_1539'),
        ('orders', '0018_auto_20210304_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlistitems',
            name='wish_variants',
            field=models.OneToOneField(default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='wishitems', to='products.Variants'),
            preserve_default=False,
        ),
    ]
