# Generated by Django 2.2 on 2021-03-10 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20210309_1539'),
        ('orders', '0019_wishlistitems_wish_variants'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='order_variants',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Variants'),
        ),
    ]
