# Generated by Django 2.2 on 2021-03-10 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_orderitem_order_variants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='order_variants',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Variants'),
        ),
    ]
