# Generated by Django 2.2 on 2021-03-10 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0021_auto_20210310_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlistitems',
            name='wish_variants',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishitems', to='products.Variants'),
        ),
    ]
