# Generated by Django 2.2 on 2021-03-10 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0021_auto_20210310_1400'),
        ('orders', '0021_auto_20210310_1529'),
    ]

    operations = [
    ]
