# Generated by Django 2.2 on 2021-03-14 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0023_auto_20210310_1226'),
        ('orders', '0022_auto_20210310_1810'),
    ]

    operations = [
    ]
