# Generated by Django 2.2 on 2021-03-21 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0024_auto_20210315_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='total_item_price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
