# Generated by Django 2.2 on 2021-03-14 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0024_merge_20210314_0636'),
        ('orders', '0023_auto_20210314_1441'),
    ]

    operations = [
    ]
