# Generated by Django 2.2 on 2021-03-25 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0025_auto_20210321_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='order_item_status',
            field=models.CharField(choices=[('To_Ship', 'To Ship'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], default='To_Ship', max_length=50),
        ),
    ]
