# Generated by Django 2.2 on 2021-03-15 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0024_auto_20210315_1223'),
        ('orders', '0025_merge_20210314_1158'),
    ]

    operations = [
    ]
