# Generated by Django 2.2 on 2021-03-21 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0025_auto_20210321_1422'),
        ('orders', '0026_merge_20210315_0915'),
    ]

    operations = [
    ]
