# Generated by Django 2.2 on 2021-03-25 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0027_merge_20210321_0856'),
        ('orders', '0026_orderitem_order_item_status'),
    ]

    operations = [
    ]
