# Generated by Django 2.2 on 2021-04-02 07:24

import apps.orders.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0028_merge_20210325_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='orderItem_ID',
            field=models.CharField(default=apps.orders.models.id_generator, editable=False, max_length=12),
        ),
    ]
