# Generated by Django 2.2 on 2021-04-02 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0029_orderitem_orderitem_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='total_item_price',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
