# Generated by Django 2.2 on 2021-04-04 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0030_auto_20210402_1600'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='total_item_price',
        ),
    ]
