# Generated by Django 2.2 on 2021-04-04 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0031_remove_orderitem_total_item_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='total_item_price',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
