# Generated by Django 2.2 on 2021-04-04 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0032_orderitem_total_item_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='total_item_price',
        ),
    ]
