# Generated by Django 2.2 on 2021-04-05 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0033_remove_orderitem_total_item_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_price',
        ),
    ]
