# Generated by Django 2.2 on 2021-04-18 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0034_remove_order_total_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billingdetails',
            old_name='country',
            new_name='area',
        ),
    ]
