# Generated by Django 2.2 on 2021-05-08 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0036_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='current_points',
            field=models.IntegerField(default=0),
        ),
    ]
