# Generated by Django 2.2 on 2021-05-09 11:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0039_auto_20210509_1338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='points',
            name='order',
        ),
        migrations.AddField(
            model_name='points',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
