# Generated by Django 2.2 on 2021-05-09 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0040_auto_20210509_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='points',
            name='points_gained',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
