# Generated by Django 2.2 on 2021-05-13 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0043_auto_20210511_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='point_spent',
            field=models.FloatField(default=0),
        ),
    ]
