# Generated by Django 2.2 on 2021-05-16 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0044_order_point_spent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('valid_form', models.DateTimeField()),
                ('valid_till', models.DateTimeField()),
                ('active', models.BooleanField()),
                ('discount', models.IntegerField()),
            ],
        ),
    ]
