# Generated by Django 2.2 on 2021-06-14 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0026_auto_20210520_1704'),
        ('orders', '0047_orderitem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupons',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to='products.Product'),
        ),
    ]
