# Generated by Django 2.2 on 2021-02-05 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='address',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='seller',
            name='business_email',
            field=models.EmailField(default=-1, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seller',
            name='business_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='seller',
            name='business_registration_no',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='seller',
            name='company_registration_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='seller',
            name='district',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='seller',
            name='docs',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='seller',
            name='full_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='seller',
            name='legal_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='seller',
            name='mob_num',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='seller',
            name='state',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='seller',
            name='vdc',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
