# Generated by Django 2.2 on 2021-02-06 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210205_1452'),
        ('accounts', '0002_auto_20210204_1639'),
    ]

    operations = [
    ]
