# Generated by Django 2.2 on 2021-02-16 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [

        ('accounts', '0003_merge_20210206_2340'),
    ]

    operations = [
    ]
