# Generated by Django 2.2 on 2021-03-17 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20210317_1545'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='full_name',
        ),
        migrations.AddField(
            model_name='seller',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='seller',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
