# Generated by Django 2.2 on 2021-03-14 08:00

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('pic_1', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Story Image (Square)')),
                ('mission', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('pic_2', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Mission Image (Sqaure)')),
                ('choose_info', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('pic_3', models.ImageField(blank=True, null=True, upload_to='')),
            ],
            options={
                'verbose_name_plural': 'About Us',
            },
        ),
    ]
