# Generated by Django 2.2 on 2021-03-15 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choose',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Icon Image')),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Choose Us Info',
            },
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='choose_info',
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='pic_3',
        ),
        migrations.AddField(
            model_name='aboutus',
            name='choose',
            field=models.ManyToManyField(blank=True, to='contacts.Choose'),
        ),
    ]
