# Generated by Django 2.2 on 2021-03-18 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_auto_20210315_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choose',
            name='icon',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='IconImage(.svg)'),
        ),
    ]
