# Generated by Django 2.2 on 2021-03-18 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_auto_20210318_1123'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_1', models.CharField(blank=True, max_length=255)),
                ('location_2', models.CharField(blank=True, max_length=255)),
                ('phone_1', models.CharField(blank=True, max_length=55)),
                ('phone_2', models.CharField(blank=True, max_length=55)),
                ('email_1', models.EmailField(blank=True, max_length=254)),
                ('email_2', models.EmailField(blank=True, max_length=254)),
                ('web_url', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name_plural': 'RupseOnline Info',
            },
        ),
    ]
